pipeline {
    agent any
    parameters {
    	booleanParam(name: 'PROMOTE', defaultValue: true, description: '')
    }
    stages {
        stage("Prebuild") {
            steps {
                script {
                    sh 'mkdir -p io_dir'
                }
            }
            post {
                success {
                    sh 'echo Prebuild successful'
                }
                failure {
                    sh 'echo Prebuild failed'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    sh '''
                    echo Build
                    
                    docker build -f dockerbuild -t devbuilder . --no-cache
                    docker run -v \$(pwd)/io_dir:/docker_vol devbuilder 
                    '''
                }
            }
            post {
                success {
                    sh 'echo Build successful'
                }
                failure {
                    sh 'echo Build failed'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh '''
                    echo Test
                    docker build . -f dockertest -t devtester
                    docker run devtester
                    '''
                }
            }
            post {
                success {
                    sh 'echo Tests successful'
                }
                failure {
                    sh 'echo Tests failed'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh '''
                    echo Deploy
                    
                    docker build . -f dockerdeploy -t devdeploy
                    docker run -d -v \$(pwd)/io_dir:/docker_vol devdeploy
                    '''
                }
            }
            post {
                success {
                    sh 'echo Deploy successful'
                }
                failure {
                    sh 'echo Deploy failed'
                }
            }
        }
	stage('Publish') {
	    when 
                {
                    expression {return params.PROMOTE}
                }
            steps {
                script {
                	archiveArtifacts artifacts: 'io_dir/typescript-starter-1.0.0.tgz', fingerprint: true
                }
            }
        }
    }
}
