pipeline {
    parameters {
	string(name: 'version', defaultValue: '1.0.0', description: '')
    }
    agent any
    
    stages {
             stage('Clone') 
        {
            steps 
            {
              sh "docker system prune --all -f"
              sh 'docker volume  create --name repo_vol'
              sh 'docker volume  create --name build_vol'
              sh "docker build -t clone . -f ./ITE/GCL04/PK401667/lab5/docker_clone"
              sh "docker run -v repo_vol:/Guess-Word-Game clone"           
            }
        }
	
}
}
