pipeline {
    agent any
    stages{
        stage('Build') {
            steps {
                echo 'BUILD'
                git branch: 'DK306669_termin2', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2022_S.git'
                dir('INO/termin2/DK306669') {
                    sh 'docker build . -f build.dockerfile -t builder'
                }
            }
        }
        stage('Tests') {
            steps {
                echo 'TESTS'
                dir('INO/termin2/DK306669') {
                    sh 'docker build . -f test.dockerfile -t tester'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'DEPLOY'
                dir('./INO/termin2/DK306669') {
                    sh 'docker build . -f build.dockerfile -t deploy'
                }
                sh 'docker run --rm --name deploy --mount type=volume,src="exit_volume",dst=/nodejs.org node bash =c "cd /nodejs.org && npm run"'
            }
        }    
          stage('Publish') {
            steps {
                echo 'PUBLISH'
                dir('INO/termin2/DK306669') {
                    sh 'docker build . -f publish.dockerfile -t publisher'
                }
                sh "docker run --volume /var/jenkins_home/workspace/PipeLine/INO/termin2/DK306669:/finalArchive publisher mv archive.tar.xz /finalArchive"
            }
        }   
    }
}
