#!/bin/bash

kubectl apply -f httpd-deployment.yaml

sleep 60

check=$(kubectl rollout status  deployment/httpd)
success="successfully"

if [[ $check == *"$success"* ]];
then
	echo "Successfully deployed"
else
	echo "Deployment failed, rolling back"
	kubectl rollout undo deployment httpd
fi
